//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerServicesProj3.BeerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Beer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Beer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BeerService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetMethodsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMethods", ReplyAction="*")]
        BeerServicesProj3.BeerService.GetMethodsResponse GetMethods(BeerServicesProj3.BeerService.GetMethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMethods", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetMethodsResponse> GetMethodsAsync(BeerServicesProj3.BeerService.GetMethodsRequest request);
        
        // CODEGEN: Generating message contract since element name beerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrice", ReplyAction="*")]
        BeerServicesProj3.BeerService.GetPriceResponse GetPrice(BeerServicesProj3.BeerService.GetPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetPriceResponse> GetPriceAsync(BeerServicesProj3.BeerService.GetPriceRequest request);
        
        // CODEGEN: Generating message contract since element name beerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPrice", ReplyAction="*")]
        BeerServicesProj3.BeerService.SetPriceResponse SetPrice(BeerServicesProj3.BeerService.SetPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.SetPriceResponse> SetPriceAsync(BeerServicesProj3.BeerService.SetPriceRequest request);
        
        // CODEGEN: Generating message contract since element name GetBeersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        BeerServicesProj3.BeerService.GetBeersResponse GetBeers(BeerServicesProj3.BeerService.GetBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetBeersResponse> GetBeersAsync(BeerServicesProj3.BeerService.GetBeersRequest request);
        
        // CODEGEN: Generating message contract since element name GetCheapestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCheapest", ReplyAction="*")]
        BeerServicesProj3.BeerService.GetCheapestResponse GetCheapest(BeerServicesProj3.BeerService.GetCheapestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCheapest", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCheapestResponse> GetCheapestAsync(BeerServicesProj3.BeerService.GetCheapestRequest request);
        
        // CODEGEN: Generating message contract since element name GetCostliestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCostliest", ReplyAction="*")]
        BeerServicesProj3.BeerService.GetCostliestResponse GetCostliest(BeerServicesProj3.BeerService.GetCostliestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCostliest", ReplyAction="*")]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCostliestResponse> GetCostliestAsync(BeerServicesProj3.BeerService.GetCostliestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMethodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMethods", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetMethodsRequestBody Body;
        
        public GetMethodsRequest() {
        }
        
        public GetMethodsRequest(BeerServicesProj3.BeerService.GetMethodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMethodsRequestBody {
        
        public GetMethodsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMethodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMethodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetMethodsResponseBody Body;
        
        public GetMethodsResponse() {
        }
        
        public GetMethodsResponse(BeerServicesProj3.BeerService.GetMethodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMethodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServicesProj3.BeerService.ArrayOfString GetMethodsResult;
        
        public GetMethodsResponseBody() {
        }
        
        public GetMethodsResponseBody(BeerServicesProj3.BeerService.ArrayOfString GetMethodsResult) {
            this.GetMethodsResult = GetMethodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrice", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetPriceRequestBody Body;
        
        public GetPriceRequest() {
        }
        
        public GetPriceRequest(BeerServicesProj3.BeerService.GetPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string beerName;
        
        public GetPriceRequestBody() {
        }
        
        public GetPriceRequestBody(string beerName) {
            this.beerName = beerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetPriceResponseBody Body;
        
        public GetPriceResponse() {
        }
        
        public GetPriceResponse(BeerServicesProj3.BeerService.GetPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetPriceResult;
        
        public GetPriceResponseBody() {
        }
        
        public GetPriceResponseBody(double GetPriceResult) {
            this.GetPriceResult = GetPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPrice", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.SetPriceRequestBody Body;
        
        public SetPriceRequest() {
        }
        
        public SetPriceRequest(BeerServicesProj3.BeerService.SetPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string beerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double newPrice;
        
        public SetPriceRequestBody() {
        }
        
        public SetPriceRequestBody(string beerName, double newPrice) {
            this.beerName = beerName;
            this.newPrice = newPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.SetPriceResponseBody Body;
        
        public SetPriceResponse() {
        }
        
        public SetPriceResponse(BeerServicesProj3.BeerService.SetPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPriceResponseBody {
        
        public SetPriceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeers", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetBeersRequestBody Body;
        
        public GetBeersRequest() {
        }
        
        public GetBeersRequest(BeerServicesProj3.BeerService.GetBeersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBeersRequestBody {
        
        public GetBeersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetBeersResponseBody Body;
        
        public GetBeersResponse() {
        }
        
        public GetBeersResponse(BeerServicesProj3.BeerService.GetBeersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServicesProj3.BeerService.Beer[] GetBeersResult;
        
        public GetBeersResponseBody() {
        }
        
        public GetBeersResponseBody(BeerServicesProj3.BeerService.Beer[] GetBeersResult) {
            this.GetBeersResult = GetBeersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheapestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheapest", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetCheapestRequestBody Body;
        
        public GetCheapestRequest() {
        }
        
        public GetCheapestRequest(BeerServicesProj3.BeerService.GetCheapestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCheapestRequestBody {
        
        public GetCheapestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheapestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheapestResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetCheapestResponseBody Body;
        
        public GetCheapestResponse() {
        }
        
        public GetCheapestResponse(BeerServicesProj3.BeerService.GetCheapestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCheapestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServicesProj3.BeerService.Beer GetCheapestResult;
        
        public GetCheapestResponseBody() {
        }
        
        public GetCheapestResponseBody(BeerServicesProj3.BeerService.Beer GetCheapestResult) {
            this.GetCheapestResult = GetCheapestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCostliestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCostliest", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetCostliestRequestBody Body;
        
        public GetCostliestRequest() {
        }
        
        public GetCostliestRequest(BeerServicesProj3.BeerService.GetCostliestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCostliestRequestBody {
        
        public GetCostliestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCostliestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCostliestResponse", Namespace="http://tempuri.org/", Order=0)]
        public BeerServicesProj3.BeerService.GetCostliestResponseBody Body;
        
        public GetCostliestResponse() {
        }
        
        public GetCostliestResponse(BeerServicesProj3.BeerService.GetCostliestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCostliestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BeerServicesProj3.BeerService.Beer GetCostliestResult;
        
        public GetCostliestResponseBody() {
        }
        
        public GetCostliestResponseBody(BeerServicesProj3.BeerService.Beer GetCostliestResult) {
            this.GetCostliestResult = GetCostliestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BeerServicesProj3.BeerService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BeerServicesProj3.BeerService.ServiceSoap>, BeerServicesProj3.BeerService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.GetMethodsResponse BeerServicesProj3.BeerService.ServiceSoap.GetMethods(BeerServicesProj3.BeerService.GetMethodsRequest request) {
            return base.Channel.GetMethods(request);
        }
        
        public BeerServicesProj3.BeerService.ArrayOfString GetMethods() {
            BeerServicesProj3.BeerService.GetMethodsRequest inValue = new BeerServicesProj3.BeerService.GetMethodsRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetMethodsRequestBody();
            BeerServicesProj3.BeerService.GetMethodsResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetMethods(inValue);
            return retVal.Body.GetMethodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetMethodsResponse> BeerServicesProj3.BeerService.ServiceSoap.GetMethodsAsync(BeerServicesProj3.BeerService.GetMethodsRequest request) {
            return base.Channel.GetMethodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetMethodsResponse> GetMethodsAsync() {
            BeerServicesProj3.BeerService.GetMethodsRequest inValue = new BeerServicesProj3.BeerService.GetMethodsRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetMethodsRequestBody();
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetMethodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.GetPriceResponse BeerServicesProj3.BeerService.ServiceSoap.GetPrice(BeerServicesProj3.BeerService.GetPriceRequest request) {
            return base.Channel.GetPrice(request);
        }
        
        public double GetPrice(string beerName) {
            BeerServicesProj3.BeerService.GetPriceRequest inValue = new BeerServicesProj3.BeerService.GetPriceRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetPriceRequestBody();
            inValue.Body.beerName = beerName;
            BeerServicesProj3.BeerService.GetPriceResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetPrice(inValue);
            return retVal.Body.GetPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetPriceResponse> BeerServicesProj3.BeerService.ServiceSoap.GetPriceAsync(BeerServicesProj3.BeerService.GetPriceRequest request) {
            return base.Channel.GetPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetPriceResponse> GetPriceAsync(string beerName) {
            BeerServicesProj3.BeerService.GetPriceRequest inValue = new BeerServicesProj3.BeerService.GetPriceRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetPriceRequestBody();
            inValue.Body.beerName = beerName;
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.SetPriceResponse BeerServicesProj3.BeerService.ServiceSoap.SetPrice(BeerServicesProj3.BeerService.SetPriceRequest request) {
            return base.Channel.SetPrice(request);
        }
        
        public void SetPrice(string beerName, double newPrice) {
            BeerServicesProj3.BeerService.SetPriceRequest inValue = new BeerServicesProj3.BeerService.SetPriceRequest();
            inValue.Body = new BeerServicesProj3.BeerService.SetPriceRequestBody();
            inValue.Body.beerName = beerName;
            inValue.Body.newPrice = newPrice;
            BeerServicesProj3.BeerService.SetPriceResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).SetPrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.SetPriceResponse> BeerServicesProj3.BeerService.ServiceSoap.SetPriceAsync(BeerServicesProj3.BeerService.SetPriceRequest request) {
            return base.Channel.SetPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.SetPriceResponse> SetPriceAsync(string beerName, double newPrice) {
            BeerServicesProj3.BeerService.SetPriceRequest inValue = new BeerServicesProj3.BeerService.SetPriceRequest();
            inValue.Body = new BeerServicesProj3.BeerService.SetPriceRequestBody();
            inValue.Body.beerName = beerName;
            inValue.Body.newPrice = newPrice;
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).SetPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.GetBeersResponse BeerServicesProj3.BeerService.ServiceSoap.GetBeers(BeerServicesProj3.BeerService.GetBeersRequest request) {
            return base.Channel.GetBeers(request);
        }
        
        public BeerServicesProj3.BeerService.Beer[] GetBeers() {
            BeerServicesProj3.BeerService.GetBeersRequest inValue = new BeerServicesProj3.BeerService.GetBeersRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetBeersRequestBody();
            BeerServicesProj3.BeerService.GetBeersResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetBeers(inValue);
            return retVal.Body.GetBeersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetBeersResponse> BeerServicesProj3.BeerService.ServiceSoap.GetBeersAsync(BeerServicesProj3.BeerService.GetBeersRequest request) {
            return base.Channel.GetBeersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetBeersResponse> GetBeersAsync() {
            BeerServicesProj3.BeerService.GetBeersRequest inValue = new BeerServicesProj3.BeerService.GetBeersRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetBeersRequestBody();
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetBeersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.GetCheapestResponse BeerServicesProj3.BeerService.ServiceSoap.GetCheapest(BeerServicesProj3.BeerService.GetCheapestRequest request) {
            return base.Channel.GetCheapest(request);
        }
        
        public BeerServicesProj3.BeerService.Beer GetCheapest() {
            BeerServicesProj3.BeerService.GetCheapestRequest inValue = new BeerServicesProj3.BeerService.GetCheapestRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetCheapestRequestBody();
            BeerServicesProj3.BeerService.GetCheapestResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetCheapest(inValue);
            return retVal.Body.GetCheapestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCheapestResponse> BeerServicesProj3.BeerService.ServiceSoap.GetCheapestAsync(BeerServicesProj3.BeerService.GetCheapestRequest request) {
            return base.Channel.GetCheapestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCheapestResponse> GetCheapestAsync() {
            BeerServicesProj3.BeerService.GetCheapestRequest inValue = new BeerServicesProj3.BeerService.GetCheapestRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetCheapestRequestBody();
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetCheapestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BeerServicesProj3.BeerService.GetCostliestResponse BeerServicesProj3.BeerService.ServiceSoap.GetCostliest(BeerServicesProj3.BeerService.GetCostliestRequest request) {
            return base.Channel.GetCostliest(request);
        }
        
        public BeerServicesProj3.BeerService.Beer GetCostliest() {
            BeerServicesProj3.BeerService.GetCostliestRequest inValue = new BeerServicesProj3.BeerService.GetCostliestRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetCostliestRequestBody();
            BeerServicesProj3.BeerService.GetCostliestResponse retVal = ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetCostliest(inValue);
            return retVal.Body.GetCostliestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCostliestResponse> BeerServicesProj3.BeerService.ServiceSoap.GetCostliestAsync(BeerServicesProj3.BeerService.GetCostliestRequest request) {
            return base.Channel.GetCostliestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BeerServicesProj3.BeerService.GetCostliestResponse> GetCostliestAsync() {
            BeerServicesProj3.BeerService.GetCostliestRequest inValue = new BeerServicesProj3.BeerService.GetCostliestRequest();
            inValue.Body = new BeerServicesProj3.BeerService.GetCostliestRequestBody();
            return ((BeerServicesProj3.BeerService.ServiceSoap)(this)).GetCostliestAsync(inValue);
        }
    }
}
